version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: ./backend.dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - JDBC_DATABASE_URL=jdbc:postgresql://postgres:5432/smartgardening
      - JDBC_DATABASE_USERNAME=admin
      - JDBC_DATABASE_PASSWORD=SuperSecure
      - PORT=8080
      - API_KEY=No-Key

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "smartgardening"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "SuperSecure"
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
